/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class DownloadHandle {
  start(): void
  pause(): void
  resume(): void
  stop(): void
  delete(): void
  state(): ModelDownloadState
  identifier(): string
  progress(): AsyncIterable<ProgressUpdate>
}

/** Thin FFI wrapper around `ModelStorage`. */
export declare class Engine {
  getCloudModels(): Promise<Array<CloudModel>>
  fetchCloudModels(): Promise<Array<CloudModel>>
  /** Returns a `DownloadHandle` for the given model identifier. */
  downloadHandle(identifier: string): DownloadHandle
  getLocalModels(): Array<LocalModel>
  getState(identifier: string): ModelDownloadState
  download(identifier: string): void
  pause(identifier: string): void
  resume(identifier: string): void
  stop(identifier: string): void
  delete(identifier: string): void
  updateRegistry(): Promise<Array<LocalModel>>
  activate(apiKey: string): Promise<LicenseStatus>
  constructor()
  createSession(modelId: ModelID, config: Config): Session
}

export declare class ProgressStream {

}

export declare class ProgressUpdate {
  /** Bytes downloaded so far. */
  completedBytes: number
  /** Total bytes expected for the download; `None` while unknown. */
  totalBytes?: number
  /** Normalised progress between 0.0 and 1.0. */
  progress: number
}

export declare class Session {
  run(input: Input, config: RunConfig, progress?: (arg: Output) => boolean | undefined | null): Output
}

export interface ClassificationFeature {
  name: string
  values: Array<string>
}

export interface CloudModel {
  readonly repoId: string
  readonly name: string
  readonly vendor: string
}

export interface Config {
  preset: Preset
  prefillStepSize: PrefillStepSize
  contextLength: ContextLength
  samplingSeed: SamplingSeed
}

export type ContextLength =
  | { type: 'Default' }
  | { type: 'Maximal' }
  | { type: 'Custom', length: number }

export type DownloaderError =
  | { type: 'Http', message: string }
  | { type: 'Io', message: string }
  | { type: 'AlreadyExists', path: string }
  | { type: 'Generic', message: string }

export declare const enum FinishReason {
  Stop = 0,
  Length = 1,
  Cancelled = 2,
  ContextLimitReached = 3
}

export type Input =
  | { type: 'Text', text: string }
  | { type: 'Messages', messages: Array<Message> }

export type LicenseStatus =
  | { type: 'NotActivated' }
  | { type: 'PaymentRequired' }
  | { type: 'GracePeriodActive' }
  | { type: 'Activated' }
  | { type: 'NetworkError' }
  | { type: 'InvalidApiKey' }
  | { type: 'SignatureMismatch' }
  | { type: 'Timeout' }
  | { type: 'HttpError', code: number }

export interface LocalModel {
  /** Unique identifier of the model in the form `<vendor>-<name>`. */
  readonly identifier: string
  /** Vendor/author of the model (e.g. "Llama"). */
  readonly vendor: string
  /** Human-readable model name without vendor (e.g. "3B-Instruct"). */
  readonly name: string
  /** Quantization type if the model is quantized (e.g. "uint4"). */
  readonly quantization?: string
  /** Optional regex to parse model output provided by the backend. */
  readonly outputParserRegex?: string
  /** Current download/installation state. */
  readonly state: ModelDownloadState
}

export interface Message {
  role: Role
  content: string
  reasoningContent?: string
}

export interface ModelDownloadState {
  /** Total size of all model files in kilobytes. */
  readonly totalKbytes: number
  /** Bytes already downloaded (meaningful in Downloading / Paused). */
  readonly downloadedKbytes: number
  /** Current phase of the download. */
  readonly phase: Phase
  /** Stringified error when `phase == Phase::Error`. */
  readonly error?: string
}

export type ModelID =
  | { type: 'Local', id: string }
  | { type: 'Cloud', id: string }

export interface Output {
  text: Text
  stats: Stats
  finishReason?: FinishReason
}

export interface ParsedText {
  chainOfThought?: string
  response?: string
}

export declare const enum Phase {
  NotDownloaded = 0,
  Downloading = 1,
  Paused = 2,
  Downloaded = 3,
  Error = 4
}

export type PrefillStepSize =
  | { type: 'Default' }
  | { type: 'Maximal' }
  | { type: 'Custom', length: number }

export type Preset =
  | { type: 'General' }
  | { type: 'Classification', feature: ClassificationFeature }
  | { type: 'Summarization' }

export declare const enum Role {
  System = 0,
  User = 1,
  Assistant = 2
}

export interface RunConfig {
  tokensLimit: number
  enableThinking: boolean
  samplingPolicy: SamplingPolicy
}

export interface RunStats {
  count: bigint
  averageDuration: number
}

export type SamplingMethod =
  | { type: 'Greedy' }
  | { type: 'Temperature', temperature: number }
  | { type: 'TopP', topP: number }

export type SamplingPolicy =
  | { type: 'Default' }
  | { type: 'Custom', value: SamplingMethod }

export type SamplingSeed =
  | { type: 'Default' }
  | { type: 'Custom', seed: number }

export interface Stats {
  prefillStats: StepStats
  generateStats?: StepStats
  totalStats: TotalStats
}

export interface StepStats {
  duration: number
  suffixLength: bigint
  tokensCount: bigint
  tokensPerSecond: number
  modelRun: RunStats
  run?: RunStats
}

export type StorageError =
  | { type: 'ModelNotDownloaded' }
  | { type: 'UnknownModel', identifier: string }
  | { type: 'Storage', message: string }
  | { type: 'MutexPoisoned', message: string }
  | { type: 'LicenseNotActivated' }

export interface Text {
  original: string
  parsed: ParsedText
}

export interface TotalStats {
  duration: number
  tokensCountInput: bigint
  tokensCountOutput: bigint
}

export declare function version(): string
