/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class ChatSession {
  run(input: Input, config: RunConfig, progress?: ((arg: Output) => boolean) | undefined | null): Output
  reset(): void
}

export declare class Engine {
  activate(apiKey: string): Promise<LicenseStatus>
  getChatModels(types: Array<ModelType>): Promise<Array<ChatModel>>
  getModelDownloadState(repoId: string): ModelDownloadState
  createModelDownloadHandle(repoId: string): ModelDownloadHandle
  constructor()
  createChatSession(model: ChatModel, config: Config): ChatSession
  registerLicenseStatusHandler(callback?: ((arg: LicenseStatus) => void) | undefined | null): void
  registerModelDownloadStateHandler(callback?: ((arg0: string, arg1: ModelDownloadState) => void) | undefined | null): void
  registerChatModelsHandler(callback?: ((arg: Array<ChatModel>) => void) | undefined | null): void
}

export declare class ModelDownloadHandle {
  identifier(): string
  download(): Promise<void>
  pause(): Promise<void>
  delete(): Promise<void>
  state(): Promise<ModelDownloadState>
  progress(): AsyncIterable<ProgressUpdate>
}

export declare class ProgressStream {

}

export declare class ProgressUpdate {
  /** Bytes downloaded so far. */
  completedBytes: number
  /** Total bytes expected for the download; `None` while unknown. */
  totalBytes?: number
  /** Normalised progress between 0.0 and 1.0. */
  progress: number
}

export type AsyncBatchSize =
  | { type: 'Default' }
  | { type: 'Custom', size: number }

export interface ChatModel {
  readonly repoId: string
  readonly type: ModelType
  readonly name: string
  readonly vendor: string
  readonly quantization?: string
  readonly outputParserRegex?: string
}

export interface ClassificationFeature {
  name: string
  values: Array<string>
}

export interface Config {
  preset: Preset
  contextMode: ContextMode
  contextLength: ContextLength
  prefillStepSize: PrefillStepSize
  samplingSeed: SamplingSeed
  asyncBatchSize: AsyncBatchSize
}

export type ContextLength =
  | { type: 'Default' }
  | { type: 'Maximal' }
  | { type: 'Custom', length: number }

export type ContextMode =
  | { type: 'None' }
  | { type: 'Static', input: Input }
  | { type: 'Dynamic' }

export declare const enum FinishReason {
  Stop = 0,
  Length = 1,
  Cancelled = 2,
  ContextLimitReached = 3
}

export type GrammarConfig =
  | { type: 'JsonSchema', schema: string }
  | { type: 'Regex', pattern: string }
  | { type: 'BuiltinJson' }

export type Input =
  | { type: 'Text', text: string }
  | { type: 'Messages', messages: Array<Message> }

export type LicenseStatus =
  | { type: 'NotActivated' }
  | { type: 'PaymentRequired' }
  | { type: 'GracePeriodActive' }
  | { type: 'Activated' }
  | { type: 'NetworkError' }
  | { type: 'InvalidApiKey' }
  | { type: 'SignatureMismatch' }
  | { type: 'Timeout' }
  | { type: 'HttpError', code: number }

export interface Message {
  role: Role
  content: string
  reasoningContent?: string
}

export declare const enum ModelDownloadPhase {
  NotDownloaded = 0,
  Downloading = 1,
  Paused = 2,
  Downloaded = 3,
  Locked = 4,
  Error = 5
}

export interface ModelDownloadState {
  /** Total size of all model files in kilobytes. */
  readonly totalKbytes: number
  /** Bytes already downloaded (meaningful in Downloading / Paused). */
  readonly downloadedKbytes: number
  /** Current phase of the download. */
  readonly phase: ModelDownloadPhase
  /** Stringified error when `phase == ModelDownloadPhase::Error`. */
  readonly error?: string
}

export type ModelStorageError =
  | { type: 'Io', message: string }
  | { type: 'Network', message: string }
  | { type: 'DownloadFailed', message: string }
  | { type: 'Download', message: string }
  | { type: 'InvalidPath', message: string }
  | { type: 'ModelNotFound', identifier: string }
  | { type: 'FileVerificationFailed', message: string }
  | { type: 'Paused' }

export declare const enum ModelType {
  Local = 0,
  Cloud = 1
}

export interface Output {
  text: Text
  stats: Stats
  finishReason?: FinishReason
}

export interface ParsedText {
  chainOfThought?: string
  response?: string
}

export type PrefillStepSize =
  | { type: 'Default' }
  | { type: 'Maximal' }
  | { type: 'Custom', length: number }

export type Preset =
  | { type: 'General' }
  | { type: 'Classification', feature: ClassificationFeature }
  | { type: 'Summarization' }

export declare const enum Role {
  System = 0,
  User = 1,
  Assistant = 2
}

export interface RunConfig {
  tokensLimit: number
  enableThinking: boolean
  samplingPolicy: SamplingPolicy
  grammarConfig?: GrammarConfig
}

export interface RunStats {
  count: bigint
  averageDuration: number
}

export type SamplingMethod =
  | { type: 'Greedy' }
  | { type: 'Stochastic', temperature?: number, topK?: number, topP?: number, minP?: number }

export type SamplingPolicy =
  | { type: 'Default' }
  | { type: 'Custom', value: SamplingMethod }

export type SamplingSeed =
  | { type: 'Default' }
  | { type: 'Custom', seed: number }

export interface Stats {
  prefillStats: StepStats
  generateStats?: StepStats
  totalStats: TotalStats
}

export interface StepStats {
  duration: number
  suffixLength: bigint
  tokensCount: bigint
  tokensPerSecond: number
  processedTokensPerSecond: number
  modelRun: RunStats
  run?: RunStats
}

export type StorageError =
  | { type: 'ModelNotDownloaded' }
  | { type: 'UnknownModel', repoId: string }
  | { type: 'Storage', message: string }
  | { type: 'MutexPoisoned', message: string }
  | { type: 'LicenseNotActivated' }

export interface Text {
  original: string
  parsed: ParsedText
}

export interface TotalStats {
  duration: number
  tokensCountInput: bigint
  tokensCountOutput: bigint
}

export declare function version(): string
